print("What do you get when you cross a nowman with a vampire?")
input()
print("Frostbite!")
print()
print("What do dentists call a astronaut\'s cavity?")
input()
print("A black hole!")
print()
print("Knock Knock")
input()
print("Who's there?")
print("Interrupting cow")
input()
print("Interrupting cow wh", end='')
print("-MOO!")
