#!/usr/bin/env python
#-*- coding: utf-8 -*-
'''
    python ==> 소프트웨어융합최신기술 part3_3, Swedish traffic sign data에서 가져온 
                                        annotations.txt와 사진데이터를 사용해서 
                                        사진에서 Traffic Sign들을 추출한 다음 
                                        Deep Learning을 사용해 무슨 표지판인지 맞춰보는 코드

    여기서 사진데이터를 다운받을 수 있다
    http://www.cvl.isy.liu.se/research/datasets/traffic-signs-dataset/
'''
import cv2
import os
import math
import numpy as np
import tensorflow as tf
from PIL import Image

img_path = 'E:\\ml_dataset\\Set1Part0\\'
img_fnames = os.listdir(img_path)

annotations = open(img_path + 'annotations.txt')
img_name = []
traffic_signs = []
for line in annotations:
    [img_name, traffic_signs] = line.split(':')
    

    
    

























