%%Setup
clearall
closeall
%%Userdefinedparams
%NoTraction
Control
accfilename=’accxnt’;
encFRfilename=’encoderFRnt’;
encinterv=1;
accbiaslen=20;
low=0.1;
high=3;
r1=100;
r2=200;
%WithTraction
Control
accfilenametrac=’accxt’;
encFRfilenametrac=’encoderFRt’;
encintervtrac=1;
accbiaslentra=20;
low=0.1;
high=3;
r1=100;
r2=200;
%%Loadvalues
%NoTraction
Control
accraw=csvread(accfilename);
acctimestamp=accraw(:,1);
accdata=accraw(:,2);
encoderFRdataraw=csvread(’encoderFRnt’);
encoderFRtimestamp=encoderFRdataraw(:,1);%Take
first
columnonly
encoderFRdata=encoderFRdataraw(:,2)−encoderFRdataraw(1,2);%Start
%WithTraction
at
zero
Control
accrawtrac=csvread(accfilenametrac);
acctimestamptrac=accrawtrac(:,1);
accdatatrac=accrawtrac(:,2);
encoderFRdatarawtrac=csvread(encFRfilenametrac);
encoderFRtimestamptrac=encoderFRdatarawtrac(:,1);%Take
first
columnonly
encoderFRdatatrac=encoderFRdatarawtrac(:,2)−encoderFRdatarawtrac(1,2);%Start
%%Calculate
reff
intom=0.0254;
rw=2.919/2;%in
rdeformed=2.76/2;%in
a=0.8105/2;%in
phi=sin(a/rw);
reff=(sin(phi)∗rw)/phi;
reffmeters=intom∗reff
%%Calculatereff∗omega
%NoTractionControl
fork=1:length(encoderFRdata)−encinterv
dt=encoderFRtimestamp(k+encinterv)−encoderFRtimestamp(k);
rate=(encoderFRdata(k+encinterv)−encoderFRdata(k))/dt;
reffomega(k)=intom∗rate∗(2∗pi∗reff)/4;
end
fork=1:length(encoderFRdata)−5
dt=encoderFRtimestamp(k+5)−encoderFRtimestamp(k);
rate=(encoderFRdata(k+5)−encoderFRdata(k))/dt;
reffomega5(k)=intom∗rate∗(2∗pi∗reff)/4!;
end

%WithTraction
Control
fork=1:length(encoderFRdatatrac)−encintervtrac
dttrac=encoderFRtimestamptrac(k+encintervtrac)−encoderFRtimestamptrac(k);
ratetrac=(encoderFRdatatrac(k+encintervtrac)−encoderFRdatatrac(k))/dttrac;
reffomegatrac(k)=intom∗ratetrac∗(2∗pi∗reff)/4;
end
fork=1:length(encoderFRdatatrac)−5
dttrac=encoderFRtimestamptrac(k+5)−encoderFRtimestamptrac(k);
ratetrac=(encoderFRdatatrac(k+5)−encoderFRdatatrac(k))/dttrac;
reffomega5trac(k)=intom∗ratetrac∗(2∗pi∗reff)/4;
end
%%CalculateEncoderTimescale
%NoTraction
Control
encodertime=encoderFRtimestamp(1:end−encinterv)−encoderFRtimestamp(1);
encodertime2=encoderFRtimestamp(1:end−5)−encoderFRtimestamp(1);
%WithTraction
Control
encodertimetrac=encoderFRtimestamptrac(1:end−encintervtrac)−encoderFRtimestamptrac(1);
encodertime2trac=encoderFRtimestamptrac(1:end−5)−encoderFRtimestamptrac(1);
%%Plot
reff∗omega
figure
holdon
plot(encodertime,reffomega,
’b’)
plot(encodertime2,reffomega5,
’r’,’Linewidth’,2)
plot(encodertimetrac,reffomegatrac,
’g’)
plot(encodertime2trac,reffomega5trac,
xlim([0
’k’,’Linewidth’,2)
2])
xlabel(’Time’,’Fontsize’,14)
ylabel(’reff∗\omega’)
title(’reff∗\omegavs.Time’)
legend(’TimeStep=1NoTraction’,’TimeStep=5NoTraction’,’TimeStep=1WithTraction’,’TimeStep=5WithTractio
%%Cutaccx
tomatchwithencodertimes
%NoTraction
first=knnsearch(accdata(:,1),
last=knnsearch(accdata(:,1),
%WithTraction
encoderFRtimestamp(1));
encoderFRtimestamp(end));
Control
firsttrac=knnsearch(accdatatrac(:,1),
lasttrac=knnsearch(accdatatrac(:,1),
%%Plot
encoderFRtimestamptrac(1));
encoderFRtimestamptrac(end));
AccelerationVs.Time
figure(2)
plot(acctimestamp,
hold
accdata,’b’,’Linewidth’,2);
all
plot(acctimestamptrac,
accdatatrac,’r’,’Linewidth’,2);
ylabel(’Acceleration’)
xlabel(’time’)
title(’Accelerationwrt.
legend(’NoTraction
%%Apply
filtering
%NoTraction
time’)
Control’,’WithTraction
onacceleration
Control’)
data
Control
F=accraw;
timestamp=F(:,1);
acc=F(:,2);
accxdt=timestamp(2:end)−timestamp(1:end−1);
d=fdesign.lowpass(’Fp,Fst,Ap,Ast’,low,high,1,40,50);
Hd=design(d,’equiripple’);
accout=filter(Hd,acc);
accout=accout−max(accout(1:accbiaslen));
smplsize=length(acc);
dt=(max(timestamp)−min(timestamp))/smplsize;
smplrate=1/dt;%Hz;
df=smplrate/smplsize;
%Traction
Control

Ftrac=accrawtrac;
timestamptrac=Ftrac(:,1);
acctrac=Ftrac(:,2);
accxdttrac=timestamptrac(2:end)−timestamptrac(1:end−1);
dtrac=fdesign.lowpass(’Fp,Fst,Ap,Ast’,low,high,1,40,50);
Hdtrac=design(dtrac,’equiripple’);
accouttrac=filter(Hdtrac,acctrac);
accouttrac=accouttrac−max(accouttrac(1:accbiaslentra));
smplsizetrac=length(acctrac);
dttrac=(max(timestamptrac)−min(timestamptrac))/smplsizetrac;
smplratetrac=1/dttrac;%Hz;
dftrac=smplratetrac/smplsizetrac;
%%Plot
Acceleration,
FrequencyDomain,andVelocity
figure(3)
sub=subplot(3,1,1);
%NoTraction
plot(acc,
hold
Control
’r’,
’linewidth’
plot(accout,’b’,
1.5);
’linewidth’
%WithTractionControl
plot(acctrac,’g’,
,
’linewidth’
plot(accouttrac,’y’,
hold
,
all
1.5);
,
’linewidth’
1.5);
,
1.5);
off;
gridon;
title(’Acceleration’)
legend(’RawSignal
(NoTraction)’,’Filtered
Signal
(NoTraction)’,’RawSignal
(WithTraction
Control)’,’Filtered
%PlotFFTprocesseddata
subplot(3,1,2)
%NoTraction
Control
validreg=ceil(smplsize
/2);
fd=fft(acc);
freqrng=0:
df
:
df∗(validreg
−1);
freqdom=fd(1:validreg);
plot(freqrng’,abs(freqdom));
hold
all
%WithTraction
Control
validregtrac=ceil(smplsizetrac
/2);
fdtrac=fft(acctrac);
freqrngtrac=0:
dftrac
:
dftrac∗(validregtrac
−1);
freqdomtrac=fdtrac(1:validregtrac);
plot(freqrngtrac’,abs(freqdomtrac));
title(’FrequencyDomain’)
legend(’NoTraction
Control’,’WithTraction
Control’)
gridon;
subplot(3,1,3)
%NoTraction
Control
vx=cumsum(accout(2:end)
.∗
accxdt);
velocitytime=timestamp(1:end−1)−timestamp(1);
plot(velocitytime,
hold
vx,
’linewidth’,
1.5);
all
%WithTraction
Control
vxtrac=cumsum(accouttrac(2:end)
.∗
accxdttrac);
velocitytimetrac=timestamptrac(1:end−1)−timestamptrac(1);
plot(velocitytimetrac,
vxtrac,
’linewidth’,
1.5);
title(’Velocity’)
legend(’NoTraction
hold
Control’,’WithTraction
Control’)
off
gridon
%%CreatingTimeArray
%NoTraction
Control
ts=timestamp(r1:r2);
vxenc=vx(r1:r2);
indxstart=knnsearch(encoderFRtimestamp,min(ts));
indxend=knnsearch(encoderFRtimestamp,max(ts));

indxdiff=indxend−indxstart+1;
tprior=linspace(min(ts),max(ts),
indxdiff);
omeganew=interp1q(tprior’,
%Assumethatthe
reffomega(indxstart:indxend)’,
P=polyfit(ttarget’,omeganew,
region
of
interest
hasthesametiming
for
r2−r1+1);
ttarget=linspace(min(ts),max(ts),
ttarget’);
1);
omegafit=P(1)∗ttarget’+P(2);
slipratio=(omegafit−vxenc)./omegafit;
ttarget=ttarget−ttarget(1);
%(WithTraction
Control)
tstrac=timestamptrac(r1:r2);
vxenctrac=vxtrac(r1:r2);
indxstarttrac=knnsearch(encoderFRtimestamptrac,min(tstrac));
%Searches
for
the
closest
matchingti
indxendtrac=knnsearch(encoderFRtimestamptrac,max(tstrac));
indxdifftrac=indxendtrac−indxstarttrac
+1;
tpriortrac=linspace(min(tstrac),max(tstrac),
indxdifftrac);
omeganewtrac=interp1q(tpriortrac’,
%Assumethatthe
region
reffomegatrac(indxstarttrac:indxendtrac)’,
P=polyfit(ttargettrac’,omeganewtrac,
of
interest
has
r2−r1+1);
ttargettrac=linspace(min(tstrac),max(tstrac),
ttargettrac’);
1);
omegafittrac=P(1)∗ttargettrac’+P(2);
slipratiotrac=(omegafittrac−vxenctrac)./omegafittrac;
ttargettrac=ttargettrac−ttargettrac(1);
%%Plot
reff∗omegaandVelocity
figure;
%NoTraction
Control
plot(ttarget’,omeganew,
hold
’r’,’Linewidth’,2)
all
plot(ttarget’,vxenc,’b’,
%WithTraction
’linewidth’,
1.5);
Control
plot(ttargettrac’,omeganewtrac,
plot(ttargettrac’,
’g’,’Linewidth’,2)
vxenctrac,’k’,
’linewidth’,
1.5);
xlabel(’Time’,’Fontsize’,14)
title(’reff
legend(’reff
%%Plot
Slip
∗\omegaandVelocity
∗\omega(NoTraction
vs.Time’)
Control)’,’velocity
Ratiovs.Time
figure;
%NoTraction
Control
plot(ttarget’,slipratio,’r’,’Linewidth’,2);
%WithTraction
hold
Control
all
plot(ttargettrac’,slipratiotrac,’b’,’Linewidth’,2);
xlabel(’Time’,’Fontsize’,14)
ylabel(’Slip
title(’Slip
Ratio’,’Fontsize’,14)
Ratio
legend(’NoTraction
vs.Time’,’Fontsize’,18)
Control’,’WithTraction
Control’)
(NoTraction
Control’,’reff
∗\omega(WithTractio!n
